
//Liste des Interventins 
export const GET_INTERVENTIONS_REQUEST = 'GET_INTERVENTIONS_REQUEST';
export const GET_INTERVENTIONS_SUCCESS = 'GET_INTERVENTIONS_SUCCESS';
export const GET_INTERVENTIONS_FAILURE = 'GET_INTERVENTIONS_FAILURE';

//Liste des Competences
export const GET_COMPETENCES_REQUEST = 'GET_COMPETENCES_REQUEST';
export const GET_COMPETENCES_SUCCESS = 'GET_COMPETENCES_SUCCESS';
export const GET_COMPETENCES_FAILURE = 'GET_COMPETENCES_FAILURE';